### PR TITLE
Unlock json version for compatibility. Quiet down rest call exceptions.

### PR DESCRIPTION
**Pull request by kainam00**
Thanks for writing this! I made a couple changes to make this work better in my application, so I figured I'd shoot over a pull request. I won't be offended if you don't think the changes make sense in the global scope of things.

### CODE REVIEW

**Comment by cparedes** [comment]
Is there a particular newer version of the JSON gem that you'd want to use instead? I'm not a huge fan of completely unpinning versions of gems and dealing with dep hell later on...

**Comment by kainam00** [comment]
1.7.7 has been working well in my environment. Dep hell is definitely not fun... Thanks!

**Comment by cparedes** [comment]
Amend the commit so it pins it on 1.7.7 with the ~> operator, and I'll merge it in.

**Comment by kainam00** [comment]
I've ended up making another change, let me do some branching and create another one so this pull request doesn't end up being a huge mess.

**Pull request closed without merging**
